### ISSUE TITLE
Error opening Sample.schema

### ISSUE THREAD

**Issue by mkaut** [rsuter/VisualJsonEditor#11]
I have just installed the editor.
When I choose "New" with the included Sample.schema, I get the following error: `Unable to cast object of type 'System.String' to type 'Newtonsoft.Json.Linq.JValue'.`

system: Windows 10 Enterprise, 64-bit

**Comment by RicoSuter** [comment]
Restart VJE and a new update should be available...

**Comment by mkaut** [comment]
Confirm fixed.
