### ISSUE TITLE
Editor-added elements at depth 3 are not accessible

### ISSUE THREAD

**Issue by mwweissmann** [rsuter/VisualJsonEditor#2]
When creating elements at depth 3 with VJE, those elements are always of value "{}" and cannot be edited.
Attached is a minimal example for observing this error (you can add elements to the "int list", but not change the value of those elements).
When the "int list"-elements are in the JSON-file already when loading it with VJE, their values show and can be edited as expected; they are also preserved when saving.

[minimal_error.json.txt](https://github.com/rsuter/VisualJsonEditor/files/142451/minimal_error.json.txt)

**Comment by RicoSuter** [comment]
Fixed in v1.3, https://github.com/rsuter/VisualJsonEditor/commit/b75ab00d111ffa4bf595f9a85230c9f94a3b8a74
