### ISSUE TITLE
Errors in using VJE src in Visual Studio 2017 Community

### ISSUE THREAD

**Issue by ewhitchu** [rsuter/VisualJsonEditor#24]
Hi,
I downloaded your latest source as I wanted to see if an enhancement was possible. I notice no changes for quite a while.
First there were unloaded NuGet packages. Reloaded them. 5 packages were back level, but initially I did not update them.
Next, the WPF designer would not load MainWiIndow because of several errors for which I cannot see the reason.
Same result after I updated the back-level NuGet packages.
I just wanted to see what is involved in turning the Schema property descriptions into a multiline word-wrapped text field. As an alternative, or as well, I would like to show any Schema (v7) $comment fields in your GUI. I use quite a few json files to configure a complex application. Using VJE has been a great help to our consultants already. I would like to improve its self-documentation in the Schema to get rid of most external documentation, as well as its value in validation and field xrefs..

Eric Whitchurch

**Comment by RicoSuter** [comment]
You need to work with the xaml directly as the designer is not working with the views

**Comment by ewhitchu** [comment]
Thanks for the response. I will look at doing that later when I have time.
