### ISSUE TITLE
Handling of type with contentEncoding

### ISSUE THREAD

**Issue by Indigo744** [rsuter/VisualJsonEditor#29]
Hello,

First of all, thank you so much for this nice tool. I love it 😺 

It seems that the editor does not handle transformation set by `contentEncoding` property, more specifically the `base64` encoding, as specified here: https://json-schema.org/understanding-json-schema/reference/non_json_data.html

Do you think the editor could handle this property? At least the `base64` one.
It would display the value decoded, but save it encoded.

What do you think?

Thanks.

**Comment by Indigo744** [comment]
When do you think a new release will be available?

Also, would it be possible to have the executable without the installer? Like for a portable installation.

**Comment by RicoSuter** [comment]
You can find the binaries in the ZIP file here:
https://ci.appveyor.com/project/rsuter/visualjsoneditor/build/artifacts

**Comment by RicoSuter** [comment]
v2.9
https://github.com/RicoSuter/VisualJsonEditor/commit/d2bc62ac9da44832d1c2fb74f6f24858db6f95b4

**Comment by Indigo744** [comment]
Yeah I know that I can get the artifacts, the only downsides to this is that I won't be able to get them in 6 months:
![image](https://user-images.githubusercontent.com/7137528/65588410-c6c6b100-df87-11e9-8b6b-d2e5afda6224.png)

Hence if I write in our doc to get the EXE from the artifacts, there is a chance that it won't be there 😦
