### ISSUE TITLE
Broken Download Link

### ISSUE THREAD

**Issue by SeekingTheSoul** [rsuter/VisualJsonEditor#40]
When I click on the download link at https://github.com/RicoSuter/VisualJsonEditor I receive the following error message:
     {"message":"Artifact not found or access denied."}

**Comment by EpicDeng** [comment]
> When I click on the download link at https://github.com/RicoSuter/VisualJsonEditor I receive the following error message:
> {"message":"Artifact not found or access denied."}

(+1) Same here

**Comment by pacificweb** [comment]
Me too, my solution was to clone and build.

**Comment by RicoSuter** [comment]
works again, after some months the build artifacts are deleted and the link doesnt work anymore
