### ISSUE TITLE
Errors editing Json file

### ISSUE THREAD

**Issue by ewhitchu** [rsuter/VisualJsonEditor#7]
Hi, I am serializing and de-serializing successfully from and to a C# object using Json.Net. No schema is used.
Visual Studio Code and NotePad++ both load and display the file happily but your product refuses with:
![image](https://cloud.githubusercontent.com/assets/11457459/17834790/6c1d5e1c-6793-11e6-902a-58be7bac13cc.png)
I don't know if you are still supporting the product but thought you should know. 
A very short extract from the file is below. There can be multiple base elements with multiple "Timesheet Lines" elements in each base element

```
[
  {
    "EmployeeID": "22241b17-164d-410e-ac96-dca8baf01d82",
    "StartDate": "2016-07-05T00:00:00",
    "EndDate": "2016-07-11T00:00:00",
    "Status": 2,
    "Hours": 0.0,
    "TimesheetLines": [
      {
        "EarningsRateID": "ae0ca6e1-359e-45f0-92f0-0cab5de3a592",
        "TrackingItemID": "00000000-0000-0000-0000-000000000000",
        "NumberOfUnits": [
          8.00000,
          7.30000,
          7.25000,
          7.50000,
          0.0,
          0.0,
          8.00000
        ]
      }
      ]
   }
]
```

**Comment by RicoSuter** [comment]
If you open this json you are asked to select a schema... You cannot use this json as schema, you need to have the schema for this data... You can use http://njsonschema.org to generate a schema for your c# class...

**Comment by ewhitchu** [comment]
Thanks. I thought your Editor would still open the json but you could then generate a schema with it. Should have read the manual!!
I have one of my clients using your Editor to maintain a json configuration file used in an Application I developed for them, but I have written a schema for that particular Json file because I wanted to provide good descriptions for them. The Visual Editor is great for that.
I used njsonschema to generate a first draft for that, and then enhanced the descriptions.
Thanks again for your great set of products.

**Comment by RicoSuter** [comment]
Yes, thats how it is meant to be used... Currently there is no api in NJsonSchema to generate a schema from JSON data...
